quarkus.oidc.health.enabled=true

# Disable default tenant
quarkus.oidc.tenant-enabled=false
quarkus.oidc.client-name=Default Tenant

quarkus.keycloak.devservices.start-with-disabled-tenant=true
quarkus.keycloak.devservices.realm-path=quarkus-realm.json
quarkus.keycloak.devservices.features=dpop,oid4vc-vci

quarkus.oidc.dpop-jwt.auth-server-url=${quarkus.oidc.auth-server-url}
quarkus.oidc.dpop-jwt.token.authorization-scheme=DPoP
quarkus.oidc.dpop-jwt.client-name=DPoP Tenant

quarkus.oidc.rar.application-type=web-app
quarkus.oidc.rar.auth-server-url=${quarkus.oidc.auth-server-url}
quarkus.oidc.rar.client-id=oid4vc-rest-api
quarkus.oidc.rar.credentials.client-secret.value=secret
quarkus.oidc.rar.authentication.rar.string-type.type=openid_credential
quarkus.oidc.rar.authentication.rar.string-type.credential_configuration_id=vc-scope-mapping
quarkus.oidc.rar.authentication.rar.array-type.locations=${quarkus.oidc.auth-server-url}

quarkus.log.category."org.htmlunit".level=ERROR
